### ISSUE TITLE
Execution of js and batch

### ISSUE THREAD

**Issue by jespoting** [ignition123/NgINX-Config-RTMP#1]
Hi, first of all thank you very much for the project. I have made the HLS server work and I am broadcasting it from OBS.

I'm using the application show. I'm quite new, in order to encode in all the resolutions indicated in the application and applied to the user I have to execute the files..:

executeStreams.js # I tried to run it with node but it didn't work.
and
ffmpeg_scale_bash.sh 

To which I've changed the ip, I don't know how to implement it so that they do the transcodings in real time.

My next steps are:

1- I deploy the hls server under nginx
2- Through OBS I broadcast on the url rtmp://x.x.x.x:1935/show
3- Through a web index.html with video.js I read the following url: https://x.x.x.x:8088/hls/stream.m3u8 #So far everything is perfect, it works and it plays the video
4- The problem is that it only works in one resolution. How can I run and implement executeStreams.js and ffmpeg_scale_bash.sh to work with my implementation?

Thank you in advance and sorry for my lack of knowledge

**Comment by jespoting** [comment]
I created a file and listened to it and when I start a broadcast from OBS it validates the user correctly.

```
const express = require("express");
const app = express();

var router = express.Router();

app.get('/rtmp_key_auth',async function(req,res){
    if(req.query.name === undefined){
    res.status(404);
    res.send('Key does not match');
    }else{
    if(req.query.name === "prueba"){
    res.status(200);
    res.send('Authenticated');
    } else{
    res.status(404);
    res.send('Key does not match');
    }}});

app.listen(3000, () => {
        console.log("El servidor está inicializado en el puerto 3000");
       });
```
What is still not clear to me is how to use "and forgive my great ignorance" the different applications.:

  "application live"
Theoretically, it's for broadcast and reproduction? When I configure it in OBS it accepts the connection but it doesn't create any sequence. I am also not clear on how to play and how to validate so that customers can play the video.

"application show"
This application does record inside /mnt/hls but I don't believe anything inside /mnt/recordings/ or /mnt/mp4s/$basename.mp4 and I don't know if it is using hls_variant either. 

Thanks in advance

**Comment by ignition123** [comment]
Will connect with u at night

**Comment by sudeepigntion** [comment]
Don't use execute stream.js as if you use that you need to handle the process termination signal like kill -9 these are not SIGINT/SIGTERM rather use the bash file with Nginx to downscale the resolution. and server HLS streaming again with Nginx server for multiple resolutions in HLS. You can use node js to do the same you can use Nodejs media stream server written by a Chinese guy or can use NGINX to tell Nodejs to execute the bash script using spawn process but remember to handle the child process else if your application is crashed all child process will become individual process and will never be killed if parent process is terminated.
